export const USER_TOKEN = 'USER_TOKEN';
export const MERCURE_TOKEN = 'MERCURE_TOKEN';
export const ACTUAL_USER = 'ACTUAL_USER';
export const USER_LOADING_LOGIN = 'USER_LOADING_LOGIN';
export const USER_LOADING_REGISTER = 'USER_LOADING_REGISTER';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_FRIENDS = 'USER_FRIENDS';
