export const USER_TOKEN = 'USER_TOKEN';
export const MERCURE_TOKEN = 'MERCURE_TOKEN';
export const ACTUAL_USER = 'ACTUAL_USER';
export const USER_LOADING_LOGIN = 'USER_LOADING_LOGIN';
export const USER_LOADING_REGISTER = 'USER_LOADING_REGISTER';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_FRIENDS = 'USER_FRIENDS';
export const USER_INSCRIPTION_FRIENDS = 'USER_INSCRIPTION_FRIENDS';
export const USERS_SEARCH_EMAIL = 'USERS_SEARCH_EMAIL';

