export const USER_TOKEN            = "USER_TOKEN";
export const USER_LOADING_LOGIN    = "USER_LOADING_LOGIN";
export const USER_LOADING_REGISTER = "USER_LOADING_REGISTER";
export const USER_LOGIN_ERROR      = "USER_LOGING_ERROR";
